language: python

sudo: required

python:
   - "2.7"
   - "3.4"
   - "3.5"

install:

   - pip install coveralls
   - pip install flake8

script:
  - sudo chmod -R 777 /home/travis/build/jadsonbr/pyreport/pyjasper/
  - flake8 pyjasper/
  - coverage run setup.py test

after_success:
  - coveralls