language: python

python:
   - "2.7"
   - "3.4"
   - "3.5"

install:
   - pip install -r requirements.txt
   - pip install flake8

script:
  - flake8 pyjasper/
  - coverage run setup.py test

after_success:
  - coveralls