language: python

sudo: required

python:
   - "2.7"
   - "3.4"
   - "3.5"
   - "3.6"

install:

   - pip install coveralls
   - pip install flake8

script:
  - sudo apt-get install default-jdk
  - flake8 pyjasper/
  - coverage run setup.py test

after_success:
  - coveralls